# Generated by Django 2.0.5 on 2018-06-13 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180612_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='文章作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=models.CharField(max_length=5000, verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_cover',
            field=models.ImageField(upload_to='cover', verbose_name='文章封面'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(verbose_name='最后修改日期'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_describe',
            field=models.CharField(max_length=50, verbose_name='文章描述'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_hits',
            field=models.IntegerField(verbose_name='点击量'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_ip',
            field=models.GenericIPAddressField(verbose_name='发布者IP地址'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(max_length=50, unique=True, verbose_name='文章标题'),
        ),
    ]
