# Generated by Django 2.0.5 on 2018-06-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180613_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=models.TextField(max_length=5000, verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_describe',
            field=models.TextField(max_length=50, verbose_name='文章描述'),
        ),
    ]
