# Generated by Django 2.0.5 on 2018-06-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180620_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20, unique=True, verbose_name='寄件人')),
                ('subject', models.TextField(max_length=100, verbose_name='主题')),
                ('message', models.TextField(max_length=1000, verbose_name='信息')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('date', models.DateTimeField(verbose_name='寄件日期')),
                ('ipaddress', models.GenericIPAddressField(verbose_name='寄件人IP地址')),
            ],
        ),
    ]
