# Generated by Django 2.0.5 on 2018-06-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_address',
            field=models.CharField(default='未获得地址信息', max_length=100, verbose_name='寄件人地址'),
        ),
    ]
